#!/usr/bin/env python3
"""
Generate an Earth-centered rotating-frame ("relative") Chebyshev ephemeris.

Relative mode fixes the Earth→Moon axis as +X (rotating frame) while keeping
real scale (Moon distance varies).

This script:
  - Reads the mission's geocentric NPZ generated by scripts/orbits.py
  - Computes spacecraft position in the Earth–Moon rotating frame for each sample
  - Compresses the rotated positions into a Chebyshev JSON file compatible with the runtime

Output:
  assets/<mission>/data/relative-<SPACECRAFT>-cheb.json

Usage:
  python scripts/generate-relative-orbits.py --mission=artemis1
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np


PROJECT_ROOT = Path(__file__).parent.parent
ASSETS_DIR = PROJECT_ROOT / "assets"
GENERATED_DIR_BASE = PROJECT_ROOT / "data-generated"


def load_config(mission_name: str) -> dict:
    cfg_path = ASSETS_DIR / mission_name / "data" / "config.json"
    if not cfg_path.exists():
        print(f"Error: config.json not found: {cfg_path}")
        sys.exit(1)
    return json.loads(cfg_path.read_text(encoding="utf-8"))


def normalize(v: np.ndarray) -> np.ndarray:
    n = np.linalg.norm(v)
    if not np.isfinite(n) or n == 0:
        raise ValueError("Cannot normalize zero/invalid vector")
    return v / n


def compute_basis_from_moon(r_em: np.ndarray, v_em: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Build a stable Earth–Moon rotating basis from geocentric Moon state.

      x̂ = normalize(r_EM)
      ẑ = normalize(r_EM × v_EM)
      ŷ = ẑ × x̂
    """
    xhat = normalize(r_em)
    zhat = normalize(np.cross(r_em, v_em))
    yhat = np.cross(zhat, xhat)
    return xhat, yhat, zhat


def rotate_positions_to_relative(
    sc_pos: np.ndarray,
    moon_pos: np.ndarray,
    moon_vel: np.ndarray,
) -> np.ndarray:
    """
    Rotate spacecraft positions into the Earth–Moon rotating frame at each sample time.

    Parameters:
      sc_pos:   (N,3) km spacecraft position relative to Earth
      moon_pos: (N,3) km Moon position relative to Earth
      moon_vel: (N,3) km/s Moon velocity relative to Earth

    Returns:
      (N,3) km positions in the rotating frame
    """
    n = sc_pos.shape[0]
    out = np.empty_like(sc_pos)

    for i in range(n):
        xhat, yhat, zhat = compute_basis_from_moon(moon_pos[i], moon_vel[i])
        p = sc_pos[i]
        out[i, 0] = float(np.dot(p, xhat))
        out[i, 1] = float(np.dot(p, yhat))
        out[i, 2] = float(np.dot(p, zhat))

    return out


def load_vectors_from_npz(npz_path: Path) -> tuple[np.ndarray, np.ndarray, np.ndarray, str]:
    """
    Load SC and MOON vectors from an orbits NPZ.

    Returns:
      jd: (N,) julian dates (TDB per HORIZONS convention used in repo)
      sc_pos: (N,3) km
      moon_pos_vel: (N,6) km and km/s (pos then vel)
      spacecraft_mnemonic: e.g. ORION, CY3, etc.
    """
    data = np.load(npz_path)

    if "SC_vectors" not in data:
        raise ValueError(f"NPZ missing SC_vectors: {npz_path}")
    if "MOON_vectors" not in data:
        raise ValueError(
            "NPZ missing MOON_vectors. Relative mode requires geocentric Moon state; "
            "ensure geo phase includes MOON in config planets.",
        )

    sc = data["SC_vectors"]
    moon = data["MOON_vectors"]

    if sc.shape != moon.shape:
        raise ValueError(f"Vector length mismatch: SC_vectors {sc.shape} vs MOON_vectors {moon.shape}")

    jd = sc["jdct"].astype(float)

    sc_pos = np.stack([sc["x"], sc["y"], sc["z"]], axis=1).astype(float)
    moon_pos = np.stack([moon["x"], moon["y"], moon["z"]], axis=1).astype(float)
    moon_vel = np.stack([moon["vx"], moon["vy"], moon["vz"]], axis=1).astype(float)

    # Spacecraft mnemonic is not in NPZ; caller derives it from mission config.
    return jd, sc_pos, moon_pos, moon_vel


def load_compressor_module():
    """
    Dynamically load scripts/compress-orbits.py to reuse its compression routines.
    """
    import importlib.util

    module_path = PROJECT_ROOT / "scripts" / "compress-orbits.py"
    spec = importlib.util.spec_from_file_location("compress_orbits", module_path)
    if spec is None or spec.loader is None:
        raise RuntimeError("Failed to load compress-orbits.py module")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate relative-mode Chebyshev ephemeris from geo NPZ")
    parser.add_argument("--mission", required=True, help="Mission folder name under assets/, e.g. artemis1")
    parser.add_argument(
        "--tolerance-km",
        type=float,
        default=5.0,
        help="Compression tolerance in km (default: 5.0; matches orbital phases)",
    )
    parser.add_argument(
        "--phase",
        default="geo",
        help="Source phase to derive relative mode from (default: geo)",
    )
    args = parser.parse_args()

    mission = args.mission
    cfg = load_config(mission)
    mnemonic = cfg.get("spacecraft_mnemonic", "SC")

    if args.phase not in cfg:
        print(f"Error: phase '{args.phase}' not found in {mission} config.json")
        sys.exit(1)

    source_orbits_base = Path(cfg[args.phase].get("orbits_file", f"{args.phase}-{mnemonic}")).name
    npz_path = GENERATED_DIR_BASE / mission / f"{source_orbits_base}.npz"
    if not npz_path.exists():
        print(f"Error: Source NPZ not found: {npz_path}")
        print("Run: python scripts/orbits.py --mission=<mission> --phase=geo")
        sys.exit(1)

    print(f"Generating relative mode for mission={mission} from {npz_path.name}")

    jd, sc_pos, moon_pos, moon_vel = load_vectors_from_npz(npz_path)
    rel_pos = rotate_positions_to_relative(sc_pos, moon_pos, moon_vel)

    # Build an in-memory NPZ-like dict for compression (match compressor's expected shape)
    # The compressor computes velocities from position deltas, so we only need jd/x/y/z.
    sc_vectors = np.zeros(
        jd.shape[0],
        dtype=[
            ("jdct", "<f8"),
            ("x", "<f8"),
            ("y", "<f8"),
            ("z", "<f8"),
            ("vx", "<f8"),
            ("vy", "<f8"),
            ("vz", "<f8"),
        ],
    )
    sc_vectors["jdct"] = jd
    sc_vectors["x"] = rel_pos[:, 0]
    sc_vectors["y"] = rel_pos[:, 1]
    sc_vectors["z"] = rel_pos[:, 2]

    # Write intermediate NPZ to data-generated for inspection/debugging
    out_base = f"relative-{mnemonic}"
    generated_out = GENERATED_DIR_BASE / mission / f"{out_base}.npz"
    np.savez_compressed(generated_out, SC_vectors=sc_vectors)
    print(f"Wrote {generated_out}")

    # Compress to Chebyshev JSON (reuse compress-orbits.py algorithms)
    compressor = load_compressor_module()
    npz_data = compressor.load_npz(generated_out)
    segments = compressor.compress_orbit_data_tolerance(npz_data, tolerance_km=args.tolerance_km)

    out_dir = ASSETS_DIR / mission / "data"
    out_dir.mkdir(parents=True, exist_ok=True)
    cheb_path = out_dir / f"{out_base}-cheb.json"

    output = {
        "format": "chebyshev-ephemeris",
        "version": "1.0",
        "metadata": {
            "source": str(generated_out.name),
            "created": datetime.now(timezone.utc).isoformat(),
            "tolerance_km": float(args.tolerance_km),
            "segments_count": len(segments),
            "coordinate_frame": "J2000",
            "units": {"time": "julian_date", "position": "km"},
            "derived_from": str(npz_path.name),
            "mode": "relative",
        },
        "time_range": {"start": float(npz_data["jd"][0]), "end": float(npz_data["jd"][-1])},
        "segments": segments,
    }

    cheb_path.write_text(json.dumps(output, indent=2), encoding="utf-8")
    print(f"Wrote {cheb_path}")


if __name__ == "__main__":
    main()

