#!/usr/bin/env python3
"""
Generate an Earth-centered rotating-frame ("relative") Chebyshev ephemeris.

Relative mode fixes the Earth→Moon axis as +X (rotating frame) while keeping
real scale (Moon distance varies).

This script:
  - Reads the mission's geocentric NPZ generated by scripts/orbits.py
  - Computes spacecraft position in the Earth–Moon rotating frame for each sample
  - Compresses the rotated positions into a Chebyshev JSON file compatible with the runtime

Output:
  assets/<mission>/data/relative-<SPACECRAFT>-cheb.json

Usage:
  python scripts/generate-relative-orbits.py --mission=artemis1
  python scripts/generate-relative-orbits.py --mission chandrayaan2 apollo11-sivb apollo10-lm
  python scripts/generate-relative-orbits.py --all --exclude artemis1
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np


PROJECT_ROOT = Path(__file__).parent.parent
ASSETS_DIR = PROJECT_ROOT / "assets"
GENERATED_DIR_BASE = PROJECT_ROOT / "data-generated"


def load_config(mission_name: str) -> dict:
    cfg_path = ASSETS_DIR / mission_name / "data" / "config.json"
    if not cfg_path.exists():
        print(f"Error: config.json not found: {cfg_path}")
        sys.exit(1)
    return json.loads(cfg_path.read_text(encoding="utf-8"))


def normalize(v: np.ndarray) -> np.ndarray:
    n = np.linalg.norm(v)
    if not np.isfinite(n) or n == 0:
        raise ValueError("Cannot normalize zero/invalid vector")
    return v / n


def compute_basis_from_moon(r_em: np.ndarray, v_em: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Build a stable Earth–Moon rotating basis from geocentric Moon state.

      x̂ = normalize(r_EM)
      ẑ = normalize(r_EM × v_EM)
      ŷ = ẑ × x̂
    """
    xhat = normalize(r_em)
    zhat = normalize(np.cross(r_em, v_em))
    yhat = np.cross(zhat, xhat)
    return xhat, yhat, zhat


def rotate_positions_to_relative(
    sc_pos: np.ndarray,
    moon_pos: np.ndarray,
    moon_vel: np.ndarray,
) -> np.ndarray:
    """
    Rotate spacecraft positions into the Earth–Moon rotating frame at each sample time.

    Parameters:
      sc_pos:   (N,3) km spacecraft position relative to Earth
      moon_pos: (N,3) km Moon position relative to Earth
      moon_vel: (N,3) km/s Moon velocity relative to Earth

    Returns:
      (N,3) km positions in the rotating frame
    """
    n = sc_pos.shape[0]
    out = np.empty_like(sc_pos)

    for i in range(n):
        xhat, yhat, zhat = compute_basis_from_moon(moon_pos[i], moon_vel[i])
        p = sc_pos[i]
        out[i, 0] = float(np.dot(p, xhat))
        out[i, 1] = float(np.dot(p, yhat))
        out[i, 2] = float(np.dot(p, zhat))

    return out


def load_vectors_from_npz(npz_path: Path) -> tuple[np.ndarray, np.ndarray, np.ndarray, str]:
    """
    Load SC and MOON vectors from an orbits NPZ.

    Returns:
      jd: (N,) julian dates (TDB per HORIZONS convention used in repo)
      sc_pos: (N,3) km
      moon_pos: (N,3) km
      moon_vel: (N,3) km/s
    """
    data = np.load(npz_path)

    if "SC_vectors" not in data:
        raise ValueError(f"NPZ missing SC_vectors: {npz_path}")
    if "MOON_vectors" not in data:
        raise ValueError(
            "NPZ missing MOON_vectors. Relative mode requires geocentric Moon state; "
            "ensure geo phase includes MOON in config planets.",
        )

    sc = data["SC_vectors"]
    moon = data["MOON_vectors"]

    if sc.shape != moon.shape:
        raise ValueError(f"Vector length mismatch: SC_vectors {sc.shape} vs MOON_vectors {moon.shape}")

    jd = sc["jdct"].astype(float)

    sc_pos = np.stack([sc["x"], sc["y"], sc["z"]], axis=1).astype(float)
    moon_pos = np.stack([moon["x"], moon["y"], moon["z"]], axis=1).astype(float)
    moon_vel = np.stack([moon["vx"], moon["vy"], moon["vz"]], axis=1).astype(float)

    return jd, sc_pos, moon_pos, moon_vel


def load_compressor_module():
    """
    Dynamically load scripts/compress-orbits.py to reuse its compression routines.
    """
    import importlib.util

    module_path = PROJECT_ROOT / "scripts" / "compress-orbits.py"
    spec = importlib.util.spec_from_file_location("compress_orbits", module_path)
    if spec is None or spec.loader is None:
        raise RuntimeError("Failed to load compress-orbits.py module")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def discover_missions() -> list[str]:
    missions: list[str] = []
    if not ASSETS_DIR.exists():
        return missions

    for entry in ASSETS_DIR.iterdir():
        if not entry.is_dir():
            continue
        if entry.name == "platform":
            continue
        if (entry / "data" / "config.json").exists():
            missions.append(entry.name)

    return sorted(missions)


def ensure_source_npz(mission: str, phase: str, npz_path: Path) -> None:
    if npz_path.exists():
        return

    print(f"Source NPZ missing: {npz_path}")
    print(f"Running: python scripts/orbits.py --mission={mission} --phase {phase}")

    subprocess.check_call(
        [
            sys.executable,
            str(PROJECT_ROOT / "scripts" / "orbits.py"),
            "--mission",
            mission,
            "--phase",
            phase,
        ],
        cwd=str(PROJECT_ROOT),
    )


def generate_relative_for_mission(*, mission: str, phase: str, tolerance_km: float, force: bool, ensure_npz: bool) -> None:
    cfg = load_config(mission)
    mnemonic = cfg.get("spacecraft_mnemonic", "SC")

    if phase not in cfg:
        raise ValueError(f"Phase '{phase}' not found in {mission} config.json")

    source_orbits_base = Path(cfg[phase].get("orbits_file", f"{phase}-{mnemonic}")).name
    npz_path = GENERATED_DIR_BASE / mission / f"{source_orbits_base}.npz"
    if ensure_npz:
        ensure_source_npz(mission, phase, npz_path)

    if not npz_path.exists():
        raise FileNotFoundError(
            f"Source NPZ not found: {npz_path}. "
            f"Run: python scripts/orbits.py --mission={mission} --phase {phase}",
        )

    out_dir = ASSETS_DIR / mission / "data"
    out_dir.mkdir(parents=True, exist_ok=True)

    out_base = f"relative-{mnemonic}"
    cheb_path = out_dir / f"{out_base}-cheb.json"
    if cheb_path.exists() and not force:
        print(f"Skipping {mission}: {cheb_path.name} already exists (use --force to overwrite)")
        return

    print(f"Generating relative mode for mission={mission} from {npz_path.name}")

    jd, sc_pos, moon_pos, moon_vel = load_vectors_from_npz(npz_path)
    rel_pos = rotate_positions_to_relative(sc_pos, moon_pos, moon_vel)

    # Build an in-memory NPZ-like dict for compression (match compressor's expected shape)
    # The compressor computes velocities from position deltas, so we only need jd/x/y/z.
    sc_vectors = np.zeros(
        jd.shape[0],
        dtype=[
            ("jdct", "<f8"),
            ("x", "<f8"),
            ("y", "<f8"),
            ("z", "<f8"),
            ("vx", "<f8"),
            ("vy", "<f8"),
            ("vz", "<f8"),
        ],
    )
    sc_vectors["jdct"] = jd
    sc_vectors["x"] = rel_pos[:, 0]
    sc_vectors["y"] = rel_pos[:, 1]
    sc_vectors["z"] = rel_pos[:, 2]

    # Write intermediate NPZ to data-generated for inspection/debugging
    generated_out = GENERATED_DIR_BASE / mission / f"{out_base}.npz"
    generated_out.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(generated_out, SC_vectors=sc_vectors)
    print(f"Wrote {generated_out}")

    # Compress to Chebyshev JSON (reuse compress-orbits.py algorithms)
    compressor = load_compressor_module()
    npz_data = compressor.load_npz(generated_out)
    segments = compressor.compress_orbit_data_tolerance(npz_data, tolerance_km=tolerance_km)

    output = {
        "format": "chebyshev-ephemeris",
        "version": "1.0",
        "metadata": {
            "source": str(generated_out.name),
            "created": datetime.now(timezone.utc).isoformat(),
            "tolerance_km": float(tolerance_km),
            "segments_count": len(segments),
            "coordinate_frame": "J2000",
            "units": {"time": "julian_date", "position": "km"},
            "derived_from": str(npz_path.name),
            "mode": "relative",
        },
        "time_range": {"start": float(npz_data["jd"][0]), "end": float(npz_data["jd"][-1])},
        "segments": segments,
    }

    cheb_path.write_text(json.dumps(output, indent=2), encoding="utf-8")
    print(f"Wrote {cheb_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate relative-mode Chebyshev ephemeris from geo NPZ")
    parser.add_argument("--mission", nargs="+", help="Mission folder name(s) under assets/, e.g. artemis1")
    parser.add_argument("--all", action="store_true", help="Generate for all missions under assets/")
    parser.add_argument("--exclude", nargs="*", default=[], help="Mission folder names to skip")
    parser.add_argument("--force", action="store_true", help="Overwrite existing relative cheb output")
    parser.add_argument("--ensure-npz", action="store_true", help="If source NPZ is missing, run scripts/orbits.py first")
    parser.add_argument(
        "--tolerance-km",
        type=float,
        default=5.0,
        help="Compression tolerance in km (default: 5.0; matches orbital phases)",
    )
    parser.add_argument(
        "--phase",
        default="geo",
        help="Source phase to derive relative mode from (default: geo)",
    )
    args = parser.parse_args()

    excludes = {e.strip() for e in (args.exclude or []) if e and isinstance(e, str)}

    if args.all:
        missions = [m for m in discover_missions() if m not in excludes]
    else:
        missions = []
        if args.mission:
            missions = [m.strip() for m in args.mission if m and isinstance(m, str)]
        missions = [m for m in missions if m not in excludes]

    if not missions:
        print("Error: No missions selected (use --mission <name...> or --all)")
        sys.exit(1)

    for mission in missions:
        try:
            generate_relative_for_mission(
                mission=mission,
                phase=args.phase,
                tolerance_km=float(args.tolerance_km),
                force=bool(args.force),
                ensure_npz=bool(args.ensure_npz),
            )
        except Exception as exc:
            print(f"Error generating relative data for {mission}: {exc}")
            sys.exit(1)


if __name__ == "__main__":
    main()
