#!/usr/bin/env python3
"""
Generate an Earth-centered rotating-frame ("relative") multi-body Chebyshev ephemeris.

Relative mode fixes the Earth->Moon axis as +X (rotating frame) while keeping
real scale (Moon distance varies).

This script:
  - Reads a mission geocentric NPZ generated by scripts/orbits.py
  - Computes rotating-frame basis from Moon geocentric state
  - Rotates SC/MOON/SUN positions into the relative frame
  - Compresses SC/MOON/SUN to Chebyshev
  - Fits FRAME_ROT quaternion coefficients per SC segment for fast runtime orientation

Output:
  assets/<mission>/data/relative-<SPACECRAFT>-cheb.json
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
from numpy.polynomial import chebyshev as cheb


PROJECT_ROOT = Path(__file__).parent.parent
ASSETS_DIR = PROJECT_ROOT / "assets"
GENERATED_DIR_BASE = PROJECT_ROOT / "data-generated"

SECONDS_PER_DAY = 86400.0


def load_config(mission_name: str) -> dict:
    cfg_path = ASSETS_DIR / mission_name / "data" / "config.json"
    if not cfg_path.exists():
        print(f"Error: config.json not found: {cfg_path}")
        sys.exit(1)
    return json.loads(cfg_path.read_text(encoding="utf-8"))


def normalize(v: np.ndarray) -> np.ndarray:
    n = np.linalg.norm(v)
    if not np.isfinite(n) or n == 0:
        raise ValueError("Cannot normalize zero/invalid vector")
    return v / n


def compute_basis_from_moon(r_em: np.ndarray, v_em: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Build a stable Earth-Moon rotating basis from geocentric Moon state.

      x_hat = normalize(r_EM)
      z_hat = normalize(r_EM x v_EM)
      y_hat = z_hat x x_hat
    """
    x_hat = normalize(r_em)
    z_hat = normalize(np.cross(r_em, v_em))
    y_hat = np.cross(z_hat, x_hat)
    return x_hat, y_hat, z_hat


def rotation_matrix_to_quaternion(rot: np.ndarray) -> np.ndarray:
    """
    Convert a 3x3 rotation matrix to quaternion [w, x, y, z].
    """
    m = rot
    trace = m[0, 0] + m[1, 1] + m[2, 2]

    if trace > 0.0:
        s = np.sqrt(trace + 1.0) * 2.0
        w = 0.25 * s
        x = (m[2, 1] - m[1, 2]) / s
        y = (m[0, 2] - m[2, 0]) / s
        z = (m[1, 0] - m[0, 1]) / s
    elif m[0, 0] > m[1, 1] and m[0, 0] > m[2, 2]:
        s = np.sqrt(1.0 + m[0, 0] - m[1, 1] - m[2, 2]) * 2.0
        w = (m[2, 1] - m[1, 2]) / s
        x = 0.25 * s
        y = (m[0, 1] + m[1, 0]) / s
        z = (m[0, 2] + m[2, 0]) / s
    elif m[1, 1] > m[2, 2]:
        s = np.sqrt(1.0 + m[1, 1] - m[0, 0] - m[2, 2]) * 2.0
        w = (m[0, 2] - m[2, 0]) / s
        x = (m[0, 1] + m[1, 0]) / s
        y = 0.25 * s
        z = (m[1, 2] + m[2, 1]) / s
    else:
        s = np.sqrt(1.0 + m[2, 2] - m[0, 0] - m[1, 1]) * 2.0
        w = (m[1, 0] - m[0, 1]) / s
        x = (m[0, 2] + m[2, 0]) / s
        y = (m[1, 2] + m[2, 1]) / s
        z = 0.25 * s

    quat = np.array([w, x, y, z], dtype=float)
    n = np.linalg.norm(quat)
    if n == 0 or not np.isfinite(n):
        raise ValueError("Invalid quaternion from rotation matrix")
    return quat / n


def compute_relative_basis_and_quaternion(
    moon_pos: np.ndarray,
    moon_vel: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """
    Returns:
      x_hat, y_hat, z_hat: (N, 3)
      q_frame: (N, 4) quaternion [w, x, y, z] for inertial->relative
    """
    n = moon_pos.shape[0]
    x_hat = np.empty_like(moon_pos)
    y_hat = np.empty_like(moon_pos)
    z_hat = np.empty_like(moon_pos)
    q_frame = np.empty((n, 4), dtype=float)

    prev_q: np.ndarray | None = None

    for i in range(n):
        xi, yi, zi = compute_basis_from_moon(moon_pos[i], moon_vel[i])
        x_hat[i] = xi
        y_hat[i] = yi
        z_hat[i] = zi

        # inertial->relative rotation matrix has rows [x_hat; y_hat; z_hat]
        rot = np.vstack([xi, yi, zi])
        q = rotation_matrix_to_quaternion(rot)

        # Enforce sign continuity (q and -q represent same rotation).
        if prev_q is not None and float(np.dot(q, prev_q)) < 0.0:
            q = -q

        q_frame[i] = q
        prev_q = q

    return x_hat, y_hat, z_hat, q_frame


def rotate_positions_to_relative(pos: np.ndarray, x_hat: np.ndarray, y_hat: np.ndarray, z_hat: np.ndarray) -> np.ndarray:
    """
    Rotate inertial coordinates to relative frame using precomputed basis vectors.
    """
    out = np.empty_like(pos)
    out[:, 0] = np.einsum("ij,ij->i", pos, x_hat)
    out[:, 1] = np.einsum("ij,ij->i", pos, y_hat)
    out[:, 2] = np.einsum("ij,ij->i", pos, z_hat)
    return out


def compute_velocity_from_positions(jd: np.ndarray, pos: np.ndarray) -> np.ndarray:
    """
    Central-difference velocity estimate in km/s.
    """
    n = len(jd)
    vel = np.zeros_like(pos)
    if n < 2:
        return vel

    dt_mid = (jd[2:] - jd[:-2]) * SECONDS_PER_DAY
    vel[1:-1] = (pos[2:] - pos[:-2]) / dt_mid[:, None]

    dt0 = (jd[1] - jd[0]) * SECONDS_PER_DAY
    vel[0] = (pos[1] - pos[0]) / dt0

    dtn = (jd[-1] - jd[-2]) * SECONDS_PER_DAY
    vel[-1] = (pos[-1] - pos[-2]) / dtn

    return vel


def build_series(jd: np.ndarray, pos: np.ndarray) -> dict:
    vel = compute_velocity_from_positions(jd, pos)
    return {
        "jd": jd,
        "x": pos[:, 0],
        "y": pos[:, 1],
        "z": pos[:, 2],
        "vx": vel[:, 0],
        "vy": vel[:, 1],
        "vz": vel[:, 2],
    }


def to_structured_vectors(jd: np.ndarray, pos: np.ndarray) -> np.ndarray:
    vel = compute_velocity_from_positions(jd, pos)
    vectors = np.zeros(
        len(jd),
        dtype=[
            ("jdct", "<f8"),
            ("x", "<f8"),
            ("y", "<f8"),
            ("z", "<f8"),
            ("vx", "<f8"),
            ("vy", "<f8"),
            ("vz", "<f8"),
        ],
    )
    vectors["jdct"] = jd
    vectors["x"] = pos[:, 0]
    vectors["y"] = pos[:, 1]
    vectors["z"] = pos[:, 2]
    vectors["vx"] = vel[:, 0]
    vectors["vy"] = vel[:, 1]
    vectors["vz"] = vel[:, 2]
    return vectors


def fit_quaternion_segments_from_reference(
    jd: np.ndarray,
    q_frame: np.ndarray,
    reference_segments: list[dict],
) -> list[dict]:
    """
    Fit quaternion components (cw,cx,cy,cz) with per-segment Chebyshev coefficients.
    Segment boundaries/degrees follow the SC relative series for deterministic behavior.
    """
    segments = []
    n = len(jd)

    for ref in reference_segments:
        t_start = float(ref["t_start"])
        t_end = float(ref["t_end"])
        deg = max(1, len(ref.get("cx", [])) - 1)

        i0 = int(np.searchsorted(jd, t_start, side="left"))
        i1 = int(np.searchsorted(jd, t_end, side="right"))
        i0 = max(0, min(i0, n - 1))
        i1 = max(i0 + 1, min(i1, n))

        t = jd[i0:i1]
        q = q_frame[i0:i1]
        if len(t) < 2:
            continue

        deg_eff = max(1, min(deg, len(t) - 1))
        t_norm = 2.0 * (t - t_start) / (t_end - t_start) - 1.0

        cw = cheb.Chebyshev.fit(t_norm, q[:, 0], deg_eff).coef.tolist()
        cx = cheb.Chebyshev.fit(t_norm, q[:, 1], deg_eff).coef.tolist()
        cy = cheb.Chebyshev.fit(t_norm, q[:, 2], deg_eff).coef.tolist()
        cz = cheb.Chebyshev.fit(t_norm, q[:, 3], deg_eff).coef.tolist()

        segments.append(
            {
                "t_start": t_start,
                "t_end": t_end,
                "cw": cw,
                "cx": cx,
                "cy": cy,
                "cz": cz,
            },
        )

    return segments


def load_vectors_from_npz(npz_path: Path) -> tuple[np.ndarray, dict[str, np.ndarray], dict[str, np.ndarray]]:
    """
    Load SC/MOON/SUN vectors from NPZ.

    Returns:
      jd
      pos_by_body: {SC|MOON|SUN -> (N,3)}
      vel_by_body: {SC|MOON|SUN -> (N,3)}
    """
    data = np.load(npz_path)

    for key in ("SC_vectors", "MOON_vectors", "SUN_vectors"):
        if key not in data:
            raise ValueError(
                f"NPZ missing {key}. Relative precompute requires SC/MOON/SUN in {npz_path}",
            )

    sc = data["SC_vectors"]
    moon = data["MOON_vectors"]
    sun = data["SUN_vectors"]

    if len(sc) != len(moon) or len(sc) != len(sun):
        raise ValueError("Vector length mismatch among SC/MOON/SUN")

    jd = sc["jdct"].astype(float)

    def pos(arr: np.ndarray) -> np.ndarray:
        return np.stack([arr["x"], arr["y"], arr["z"]], axis=1).astype(float)

    def vel(arr: np.ndarray) -> np.ndarray:
        return np.stack([arr["vx"], arr["vy"], arr["vz"]], axis=1).astype(float)

    pos_by_body = {
        "SC": pos(sc),
        "MOON": pos(moon),
        "SUN": pos(sun),
    }
    vel_by_body = {
        "SC": vel(sc),
        "MOON": vel(moon),
        "SUN": vel(sun),
    }
    return jd, pos_by_body, vel_by_body


def load_compressor_module():
    import importlib.util

    module_path = PROJECT_ROOT / "scripts" / "compress-orbits.py"
    spec = importlib.util.spec_from_file_location("compress_orbits", module_path)
    if spec is None or spec.loader is None:
        raise RuntimeError("Failed to load compress-orbits.py module")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def discover_missions() -> list[str]:
    missions: list[str] = []
    if not ASSETS_DIR.exists():
        return missions

    for entry in ASSETS_DIR.iterdir():
        if not entry.is_dir():
            continue
        if entry.name == "platform":
            continue
        if (entry / "data" / "config.json").exists():
            missions.append(entry.name)

    return sorted(missions)


def ensure_source_npz(mission: str, phase: str, npz_path: Path) -> None:
    if npz_path.exists():
        return

    print(f"Source NPZ missing: {npz_path}")
    print(f"Running: python scripts/orbits.py --mission={mission} --phase {phase}")

    subprocess.check_call(
        [
            sys.executable,
            str(PROJECT_ROOT / "scripts" / "orbits.py"),
            "--mission",
            mission,
            "--phase",
            phase,
        ],
        cwd=str(PROJECT_ROOT),
    )


def generate_relative_for_mission(*, mission: str, phase: str, tolerance_km: float, force: bool, ensure_npz: bool) -> None:
    cfg = load_config(mission)
    mnemonic = cfg.get("spacecraft_mnemonic", "SC")

    if phase not in cfg:
        raise ValueError(f"Phase '{phase}' not found in {mission} config.json")

    source_orbits_base = Path(cfg[phase].get("orbits_file", f"{phase}-{mnemonic}")).name
    npz_path = GENERATED_DIR_BASE / mission / f"{source_orbits_base}.npz"
    if ensure_npz:
        ensure_source_npz(mission, phase, npz_path)

    if not npz_path.exists():
        raise FileNotFoundError(
            f"Source NPZ not found: {npz_path}. "
            f"Run: python scripts/orbits.py --mission={mission} --phase {phase}",
        )

    out_dir = ASSETS_DIR / mission / "data"
    out_dir.mkdir(parents=True, exist_ok=True)

    out_base = f"relative-{mnemonic}"
    cheb_path = out_dir / f"{out_base}-cheb.json"
    if cheb_path.exists() and not force:
        print(f"Skipping {mission}: {cheb_path.name} already exists (use --force to overwrite)")
        return

    print(f"Generating relative mode for mission={mission} from {npz_path.name}")

    jd, pos_by_body, vel_by_body = load_vectors_from_npz(npz_path)
    moon_pos = pos_by_body["MOON"]
    moon_vel = vel_by_body["MOON"]

    x_hat, y_hat, z_hat, q_frame = compute_relative_basis_and_quaternion(moon_pos, moon_vel)

    rel_pos_by_body = {
        body_id: rotate_positions_to_relative(pos, x_hat, y_hat, z_hat)
        for body_id, pos in pos_by_body.items()
    }

    # Write intermediate NPZ to data-generated for inspection/debugging.
    generated_out = GENERATED_DIR_BASE / mission / f"{out_base}.npz"
    generated_out.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        generated_out,
        SC_vectors=to_structured_vectors(jd, rel_pos_by_body["SC"]),
        MOON_vectors=to_structured_vectors(jd, rel_pos_by_body["MOON"]),
        SUN_vectors=to_structured_vectors(jd, rel_pos_by_body["SUN"]),
        FRAME_ROT=q_frame,
    )
    print(f"Wrote {generated_out}")

    compressor = load_compressor_module()

    body_cheb = {}
    total_segments = 0
    for body_id in ("SC", "MOON", "SUN"):
        body_series = build_series(jd, rel_pos_by_body[body_id])
        body_segments = compressor.compress_orbit_data_tolerance(
            body_series,
            tolerance_km=tolerance_km,
        )
        body_cheb[body_id] = {
            "time_range": {
                "start": float(jd[0]),
                "end": float(jd[-1]),
            },
            "segments": body_segments,
        }
        total_segments += len(body_segments)

    frame_segments = fit_quaternion_segments_from_reference(
        jd=jd,
        q_frame=q_frame,
        reference_segments=body_cheb["SC"]["segments"],
    )
    total_segments += len(frame_segments)

    output = {
        "format": "chebyshev-ephemeris",
        "version": "1.0",
        "metadata": {
            "source": str(generated_out.name),
            "created": datetime.now(timezone.utc).isoformat(),
            "tolerance_km": float(tolerance_km),
            "segments_count": int(total_segments),
            "bodies": ["SC", "MOON", "SUN", "FRAME_ROT"],
            "coordinate_frame": "relative-earth-moon",
            "units": {"time": "julian_date", "position": "km"},
            "derived_from": str(npz_path.name),
            "mode": "relative",
            "frame_definition": "x=Earth->Moon, z=angular-momentum, y=z×x",
        },
        "time_range": {"start": float(jd[0]), "end": float(jd[-1])},
        "SC": body_cheb["SC"],
        "MOON": body_cheb["MOON"],
        "SUN": body_cheb["SUN"],
        "FRAME_ROT": {
            "time_range": {"start": float(jd[0]), "end": float(jd[-1])},
            "segments": frame_segments,
        },
    }

    cheb_path.write_text(json.dumps(output, indent=2), encoding="utf-8")
    print(f"Wrote {cheb_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate relative-mode Chebyshev ephemeris from geo NPZ")
    parser.add_argument("--mission", nargs="+", help="Mission folder name(s) under assets/, e.g. artemis1")
    parser.add_argument("--all", action="store_true", help="Generate for all missions under assets/")
    parser.add_argument("--exclude", nargs="*", default=[], help="Mission folder names to skip")
    parser.add_argument("--force", action="store_true", help="Overwrite existing relative cheb output")
    parser.add_argument("--ensure-npz", action="store_true", help="If source NPZ is missing, run scripts/orbits.py first")
    parser.add_argument(
        "--tolerance-km",
        type=float,
        default=5.0,
        help="Compression tolerance in km (default: 5.0; matches orbital phases)",
    )
    parser.add_argument(
        "--phase",
        default="geo",
        help="Source phase to derive relative mode from (default: geo)",
    )
    args = parser.parse_args()

    excludes = {e.strip() for e in (args.exclude or []) if e and isinstance(e, str)}

    if args.all:
        missions = [m for m in discover_missions() if m not in excludes]
    else:
        missions = []
        if args.mission:
            missions = [m.strip() for m in args.mission if m and isinstance(m, str)]
        missions = [m for m in missions if m not in excludes]

    if not missions:
        print("Error: No missions selected (use --mission <name...> or --all)")
        sys.exit(1)

    for mission in missions:
        try:
            generate_relative_for_mission(
                mission=mission,
                phase=args.phase,
                tolerance_km=float(args.tolerance_km),
                force=bool(args.force),
                ensure_npz=bool(args.ensure_npz),
            )
        except Exception as exc:
            print(f"Error generating relative data for {mission}: {exc}")
            sys.exit(1)


if __name__ == "__main__":
    main()
